version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: weather
    volumes:
      - "./configs/database.sql:/docker-entrypoint-initdb.d/database.sql"

  api:
    build: .
    dns:
      - 8.8.8.8
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=weather
      - DB_ADDRESS=db:5432
      - OPEN_WEATHER_MAP_TOKEN=${OPEN_WEATHER_MAP_TOKEN}
      - OPEN_WEATHER_MAP_URL=http://api.openweathermap.org/data/2.5